# Generated by Django 3.2.3 on 2023-11-01 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(2, message='Максимум 2 символа')], verbose_name='Нижняя граница возрастной группы')),
                ('year_until', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(2, message='Максимум 2 символа')], verbose_name='Верхняя граница возрастной группы')),
            ],
            options={
                'verbose_name': 'Возрастная группа',
                'verbose_name_plural': 'Возрастные группы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Day_of_week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Название секции')),
                ('gender', models.CharField(blank=True, max_length=7, verbose_name='Пол детей')),
                ('aviable', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(3, message='Максимум 3 символа')], verbose_name='Наличие свободных мест')),
                ('price', models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ'), django.core.validators.MaxLengthValidator(6, message='Максимум 6 символов')], verbose_name='Стоимость посещения секции в месяц в рублях')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.address', verbose_name='Адрес секции')),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.age_group', verbose_name='Возрастная группа')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ('sports_organization', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Sport_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вида спорта')),
            ],
            options={
                'verbose_name': 'Название вида спорта',
                'verbose_name_plural': 'Название видов спорта',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Фамилия Имя Отчество')),
                ('info', models.TextField(blank=True, max_length=10000, verbose_name='Информация о тренере')),
                ('photo', models.ImageField(upload_to='img/trainers', verbose_name='Фотография тренера')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.TimeField(verbose_name='Время начала')),
                ('time_until', models.TimeField(verbose_name='Время окончания')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.day_of_week', verbose_name='День недели')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Section_and_Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Секция')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Секция и тренер',
                'verbose_name_plural': 'Секции и тренера',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='section',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sport_type', verbose_name='Вид спорта'),
        ),
        migrations.AddField(
            model_name='section',
            name='sports_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Спортивная школа'),
        ),
        migrations.CreateModel(
            name='Photo_of_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='img/sections', verbose_name='Фотография секции')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Phone_of_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.phone_number', verbose_name='Номер телефона')),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Секция спортивной школы')),
            ],
        ),
    ]
