# Generated by Django 3.2.3 on 2023-11-06 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_auto_20231106_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='aviable',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(999, message='Максимальное значение 999')], verbose_name='Наличие свободных мест'),
        ),
        migrations.AlterField(
            model_name='section',
            name='price',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MaxValueValidator(99999, message='Максимальное значение 99999')], verbose_name='Стоимость посещения секции в месяц в рублях'),
        ),
    ]
