# Generated by Django 3.2.3 on 2023-11-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20231106_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='gender',
            field=models.CharField(blank=True, choices=[('Man', 'Мужской'), ('Woman', 'Женский')], max_length=7, verbose_name='Пол детей'),
        ),
    ]
