# Generated by Django 3.2.3 on 2023-11-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_section_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shedule',
            name='day',
        ),
        migrations.AddField(
            model_name='shedule',
            name='day',
            field=models.ManyToManyField(to='sections.DayOfWeek', verbose_name='День недели'),
        ),
    ]
