# Generated by Django 3.2.3 on 2023-11-06 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20231106_1535'),
        ('sections', '0005_auto_20231106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.address', verbose_name='Адрес секции'),
        ),
    ]
