# Generated by Django 3.2.3 on 2023-11-06 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_alter_section_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='age_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.agegroup', verbose_name='Возрастная группа'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sport_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sections.sporttype', verbose_name='Вид спорта'),
        ),
    ]
