# Generated by Django 3.2.3 on 2023-11-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0007_auto_20231106_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayofweek',
            options={'verbose_name': 'День недели', 'verbose_name_plural': 'Дни недели'},
        ),
        migrations.AlterModelOptions(
            name='sectiontrainer',
            options={'verbose_name': 'Секция и тренер', 'verbose_name_plural': 'Секции и тренера'},
        ),
    ]
