version: '3.8'

services:
  db:
    image: postgres:16.1
    env_file:
      - ./.env
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    image: yasporthub/backend
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    image: yasporthub/frontend
    env_file:
      - ./.env
    depends_on:
      - backend
    volumes:
      - frontend_data:/app/dist/

  nginx:
    image: nginx:1.25.3
    ports:
      - "8000:80"
    depends_on:
      - frontend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
      - media:/var/html/media/
      - frontend_data:/usr/share/nginx/html/

volumes:
  db_data:
  static:
  media:
  frontend_data:
