# Generated by Django 3.2.3 on 2023-11-12 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Неправильный формат индекса', regex='^\\d{6}$')], verbose_name='Индекс')),
                ('city', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2, message='Минимум 2 символа')], verbose_name='Город')),
                ('metro', models.CharField(blank=True, max_length=65, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Метро')),
                ('district', models.CharField(max_length=65, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Район')),
                ('street', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Улица')),
                ('house', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1, message='Минимум 1 символ')], verbose_name='Дом')),
                ('location', models.TextField()),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('city', 'street', 'house'),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов')], verbose_name='Номер телефона')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='Комментарий к номеру телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='SportOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Название организации')),
                ('logo', models.ImageField(blank=True, upload_to='img/organizations', verbose_name='Логотип организации')),
                ('email', models.EmailField(max_length=320, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Адрес электронной почты')),
                ('site', models.URLField(blank=True, max_length=255, verbose_name='Сайт или страничка в VK')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание организации')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.address', verbose_name='Адрес спортивной школы')),
            ],
            options={
                'verbose_name': 'Спортивная школа',
                'verbose_name_plural': 'Спортивные школы',
            },
        ),
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Текст отзыва')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время оставления отзыва')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимумальное значение 1'), django.core.validators.MaxValueValidator(5, message='Максимальное значение 5')], verbose_name='Рейтинг')),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sportorganization', verbose_name='Спортивная школа')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='PhoneOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.phonenumber', verbose_name='Телефон')),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sportorganization', verbose_name='Спортивная школа')),
            ],
            options={
                'verbose_name': 'Телефон спортшколы',
                'verbose_name_plural': 'Телефоны спортшколы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Фамилия Имя Отчество')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1'), django.core.validators.MaxValueValidator(99, message='Максимальное значение 99')], verbose_name='Возраст ребенка')),
                ('gender', models.CharField(choices=[('Man', 'Мужской'), ('Woman', 'Женский')], max_length=7, verbose_name='Пол ребенка')),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов')], verbose_name='Номер телефона для связи')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий к заявке')),
                ('sport_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sportorganization', verbose_name='Спортивная школа')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
