# Generated by Django 4.2.7 on 2023-12-10 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов')], verbose_name='Номер телефона')),
                ('comment', models.CharField(blank=True, max_length=30, verbose_name='Комментарий к номеру телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.CreateModel(
            name='SportOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Название организации')),
                ('logo', models.ImageField(blank=True, upload_to='img/organizations', verbose_name='Логотип организации')),
                ('address', models.CharField(max_length=350, verbose_name='Адрес спортивной школы')),
                ('email', models.EmailField(max_length=320, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Адрес электронной почты')),
                ('site', models.URLField(blank=True, max_length=255, verbose_name='Сайт или страничка в VK')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание спортивной школы')),
            ],
            options={
                'verbose_name': 'Спортивная школа',
                'verbose_name_plural': 'Спортивные школы',
            },
        ),
        migrations.CreateModel(
            name='PhoneOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.phonenumber', verbose_name='Телефон')),
                ('sport_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sportorganization', verbose_name='Спортивная школа')),
            ],
            options={
                'verbose_name': 'Телефон спортшколы',
                'verbose_name_plural': 'Телефоны спортшколы',
            },
        ),
    ]
