# Generated by Django 3.2.3 on 2023-11-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='all_fields',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
