# Generated by Django 3.2.3 on 2023-11-06 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='value',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов'), django.core.validators.RegexValidator(message='Неправильный формат номера телефона.', regex='^\\+7\\(\\d{3}\\)\\d{7}$')], verbose_name='Номер телефона'),
        ),
    ]
