# Generated by Django 3.2.3 on 2023-11-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_phonenumber_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='value',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов')], verbose_name='Номер телефона'),
        ),
    ]
