# Generated by Django 3.2.3 on 2023-11-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_phonenumber_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='img/organizations', verbose_name='Логотип организации'),
        ),
    ]
