# Generated by Django 3.2.3 on 2023-11-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_remove_address_all_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Полный адрес'),
        ),
    ]
