# Generated by Django 3.2.3 on 2023-11-06 08:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_sportorganization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneoforganization',
            name='sport_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.sportorganization', verbose_name='Спортивная школа'),
        ),
        migrations.AlterField(
            model_name='rewiev',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимумальное значение 1'), django.core.validators.MaxValueValidator(5, message='Максимальное значение 5')], verbose_name='Рейтинг'),
        ),
    ]
