# Generated by Django 3.2.3 on 2023-11-11 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_address_full_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов')], verbose_name='Индекс'),
        ),
    ]
