# Generated by Django 3.2.3 on 2023-11-11 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20231111_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.CharField(blank=True, max_length=350, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.RegexValidator(message='Индекс может содержать только цифры.', regex='^\\d{6}$')], verbose_name='Индекс'),
        ),
    ]
