# Generated by Django 3.2.3 on 2023-11-06 09:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20231106_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Логин может содержать только символы английского алфавита.', regex='^[a-z]+$')], verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='phoneoforganization',
            name='sport_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.sportorganization', verbose_name='Спортивная школа'),
        ),
        migrations.AlterField(
            model_name='sportorganization',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.address', verbose_name='Адрес спортивной школы'),
        ),
    ]
