# Generated by Django 3.2.3 on 2023-11-06 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20231106_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Неправильный формат индекса', regex='\\d{6}')], verbose_name='Индекс'),
        ),
    ]
