# Generated by Django 3.2.3 on 2023-11-11 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20231111_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewiev',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='fio',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.RegexValidator(message='Неправильный формат ФИО.', regex='^[А-Я][а-я]+\\s[А-Я][а-я]+\\s[А-Я][а-я]+$')], verbose_name='Фамилия Имя Отчество'),
        ),
    ]
