# Generated by Django 3.2.3 on 2023-11-11 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20231111_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewiev',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
