# Generated by Django 3.2.3 on 2023-11-06 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_address_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Неправильный формат индекса', regex='^\\d{6}$')], verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение 1'), django.core.validators.MaxValueValidator(99, message='Максимальное значение 99')], verbose_name='Возраст ребенка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к заявке'),
        ),
        migrations.AlterField(
            model_name='order',
            name='gender',
            field=models.CharField(choices=[('Man', 'Мужской'), ('Woman', 'Женский')], max_length=7, verbose_name='Пол ребенка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(14, message='Минимум 14 символов')], verbose_name='Номер телефона для связи'),
        ),
    ]
