# Generated by Django 3.2.3 on 2023-11-08 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.RegexValidator(message='Логин может содержать только символы английского алфавита.', regex='^[a-z]+$')], verbose_name='Логин'),
        ),
    ]
