# Generated by Django 4.2.7 on 2023-12-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.UUIDField(default='', editable=False, unique=True),
        ),
    ]
