# Generated by Django 4.2.7 on 2023-12-12 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
